### ISSUE TITLE
训练需要的模型文件没有上传？

### ISSUE THREAD

**Issue by Blxzxb** [maijia181614/Chinese-Takeaway-Review-Text-Classification#1]
BERT_MODEL = torch.load(save_path + 'bert_model_train.pth')
File "C:\software\anaconda\envs\torch\lib\site-packages\torch\serialization.py", line 699, in load
with _open_file_like(f, 'rb') as opened_file:
File "C:\software\anaconda\envs\torch\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
return _open_file(name_or_buffer, mode)
File "C:\software\anaconda\envs\torch\lib\site-packages\torch\serialization.py", line 211, in init
super(_open_file, self).init(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './model/bert_model_train.pth'

**Comment by maijia181614** [comment]
Hello, 因为我没有上传模型文件，应该是需要先到https://github.com/ymcui/chinese-bert-wwm 下载训练模型，然后先跑一遍原始bert_model得到bert_model_train.pth再去跑其他选项。

**Comment by WoShiSiWaWang** [comment]
> Hello, 因为我没有上传模型文件，应该是需要先到https://github.com/ymcui/chinese-bert-wwm 下载训练模型，然后先跑一遍原始bert_model得到bert_model_train.pth再去跑其他选项。

怎样获得bert_model_train.pth？不是下载得到的都是pytorch_model.bin文件吗？  能否具体说下是运行哪个得到pth的？

**Comment by Blxzxb** [comment]
下载好bert模型跑一遍bert_model的训练代码就可以了

**Comment by WoShiSiWaWang** [comment]
> 下载好bert模型跑一遍bert_model的训练代码就可以了

非常感谢
